---
- name: Install NetworkManager
  hosts: all
  become: true
  tasks:
    - name: Update apt package index
      ansible.builtin.apt:
        update_cache: yes

    - name: Install NetworkManager package
      ansible.builtin.apt:
        name: network-manager
        state: present
      when: ansible_facts['os_family'] == "Debian"

    - name: Ensure NetworkManager service is started and enabled
      ansible.builtin.service:
        name: NetworkManager
        state: started
        enabled: true
